apiVersion: apps/v1
kind: Deployment
metadata:
  name: tam-aks-learn-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tam-aks-learn-service
  template:
    metadata:
      labels:
        app: tam-aks-learn-service
    spec:
      containers:
      - name: tam-aks-learn-service
        image: tamilacr.azurecr.io/tam-aks-learn-service:v1
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: tam-aks-learn-service
spec:
  selector:
    app: tam-aks-learn-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
